site_name: Understanding Analysis by Stephen Abbot (2nd Ed)
theme: readthedocs

nav:
  - Home: index.md
  - Chapter 03 Notes: ch03notes.md
  - Chapter 03 Exercises: ch03ex.md
  - Chapter 04 Notes: ch04notes.md
  - Chapter 04 Exercises: ch04ex.md
  - Chapter 05 Notes: ch05notes.md
  - Chapter 05 Exercises: ch05ex.md
  - Chapter 06 Notes: ch06notes.md
  - Chapter 06 Exercises: ch06ex.md
  - Misc info: misc.md
  - Unsolved Problems: unsolved.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    # - pymdownx.arithmatex:
    #     generic: true

repo_name: Github
repo_url: https://github.com/eroicaleo/abbot-analysis-2nd/
edit_uri: 'blob/main/docs/'
