site_name: Understanding Analysis by Stephen Abbot (2nd Ed)
theme: readthedocs

nav:
  - Home: index.md
  - Chapter 03 Exercises: ch03ex.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
