site_name: Understanding Analysis by Stephen Abbot (2nd Ed)
theme: readthedocs

nav:
  - Home: index.md
  - Chapter 03 Notes: ch03notes.md
  - Chapter 03 Exercises: ch03ex.md
  - Chapter 04 Notes: ch04notes.md
  - Chapter 04 Exercises: ch04ex.md
  - Misc info: misc.md
  - Unsolved Problems: unsolved.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

repo_name: Github
repo_url: https://github.com/eroicaleo/abbot-analysis-2nd/
edit_uri: 'blob/main/docs/'
